server:
  port: 8082
  servlet:
    context-path: /test

school.name: 天竹小学666
school.web: www.hao123.com

#指定mapper文件的位置
mybatis.mapper-locations: classpath:mapper/*.xml

#指定mybatis的日志
mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


